### ISSUE TITLE
Module dosnt load

### ISSUE THREAD

**Issue by andlo** [MSAdministrator/PoshZD#5]
For some strange reason I cant import-module

No errors, but module isnt loaded :( 

Any Idea what I am doing wrong or how to figure out what is wrong ?

**Comment by MSAdministrator** [comment]
Hmm, okay. Let me take a look. It might be this evening or tomorrow, but I'll take a look and update this issue.

**Comment by MSAdministrator** [comment]
Hey @andlo I have updated the module and it should be good to go.  I'm waiting for AppVeyor to build, but it should be good to go.  You can modify the .psm1 file to create a custom base configuration for the imported module or you can use a new function called Set-ZDConfiguration after you have imported the module.  Let me know if you run into any issues.
