### ISSUE TITLE
Module OSS License (LICENSE file)

### ISSUE THREAD

**Issue by sintaxasn** [MSAdministrator/PoshZD#6]
Hi there,

Do you have a a license agreement for this project? I'd like to be able to use myself, however my company has pretty strict guidelines on open-source software and requiring some sort of license agreement as part of the project, e.g. Apache 2.0 license.

Thanks in advance!

Dan

**Comment by MSAdministrator** [comment]
@sintaxasn  I just added a license in #7 - went with MIT - So sorry for the delayed response.
