### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by tbasten** [MSAdministrator/PoshZD#8]
Hi,

I am getting the following error when I try and connect. Below is what I have set for the variables

Set-ZDHeader -Email 'MyEmail' -Token 'API Token'
Set-ZDDomain -Domain 'https://ourdomain.zendesk.com' 

I have also tried Set-ZDDomain -Domain 'ourdomain'  but it returns the same error.

```
Invoke-RestMethod : The underlying connection was closed: An unexpected error occurred on a send.
At D:\Powershell\Modules\PoshZD-master\PoshZD\Public\Tickets\Get-ZDTicket.ps1:43 char:33
+         $ReturnObject.ticket = (Invoke-RestMethod @params).ticket
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by MSAdministrator** [comment]
@tbasten Can you try and run the following and tell me the output?  Of course you don't have to provide the actual domain or header/token but just tell me if you get an error:

```Powershell
$Domain
$Headers
```

I am looking into this, but I don't have access to a ZenDesk instance at this time so looking through documentation to see if ZD changed their API.

**Comment by tbasten** [comment]
Hi,

I get the following.
$Domain -> Contoso
$Headers -> Authorization                  Basic  [followed by a long string].

**Comment by MSAdministrator** [comment]
@tbasten I just got a “sponsored” account from ZenDesk support to continue development! With that said, I plan on looking at this sometime either this weekend or next week. Sorry for the issues but I’ll get it fixed soon.

**Comment by MSAdministrator** [comment]
@tbasten This should be fixed now.  Please let me know if you have any additional issues.  Sorry for the delay.
